<a href="https://colab.research.google.com/github/Sasha-Kirsten/Session-1-Homework/blob/main/Session_1_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.21.6'

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-05 19:57:38--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  --.-KB/s    in 0.04s   

2022-09-05 19:57:38 (39.9 MB/s) - ‘data.csv’ saved [1475504/1475504]



In [4]:
df = pd.read_csv('data.csv')
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [ ]:
# 11914 rows

In [5]:
newData = df.groupby('Make').count().sort_values('Popularity',ascending=False)
newData

Model  Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
Make                                                                        
Chevrolet       1123  1123              1123       1117              1121   
Ford             881   881               881        868               881   
Volkswagen       809   809               809        809               805   
Toyota           746   746               746        744               745   
Dodge            626   626               626        626               626   
Nissan           558   558               558        548               558   
GMC              515   515               515        515               515   
Honda            449   449               449        447               449   
Mazda            423   423               423        423               403   
Cadillac         397   397               397        397               397   
Mercedes-Benz    353   353               353        352               353   
Suzuki           351   351               348        351               351   
BMW              334   334               334        334               334   
Infiniti         330   330               330        330               330   
Audi             328   328               328        328               328   
Hyundai          303   303               303        303               303   
Volvo            281   281               281        281               281   
Subaru           256   256               256        256               256   
Acura            252   252               252        252               252   
Kia              231   231               231        226               231   
Mitsubishi       213   213               213        212               210   
Lexus            202   202               202        202               202   
Buick            196   196               196        196               196   
Chrysler         187   187               187        187               187   
Pontiac          186   186               186        186               186   
Lincoln          164   164               164        156               164   
Oldsmobile       150   150               150        150               150   
Land Rover       143   143               143        143               143   
Porsche          136   136               136        136               136   
Saab             111   111               111        111               111   
Aston Martin      93    93                93         93                93   
Plymouth          82    82                82         82                82   
Bentley           74    74                74         74                74   
Ferrari           69    69                69         69                69   
FIAT              62    62                62         59                62   
Scion             60    60                60         60                60   
Maserati          58    58                58         58                58   
Lamborghini       52    52                52         52                52   
Rolls-Royce       31    31                31         31                31   
Lotus             29    29                29         29                29   
Tesla             18    18                18          0                18   
HUMMER            17    17                17         17                17   
Maybach           16    16                16         16                16   
McLaren            5     5                 5          5                 5   
Alfa Romeo         5     5                 5          5                 5   
Spyker             3     3                 3          3                 3   
Bugatti            3     3                 3          3                 3   
Genesis            3     3                 3          3                 3   

               Transmission Type  Driven_Wheels  Number of Doors  \
Make                                                               
Chevrolet                   

In [ ]:
# Chevrolet, Ford, Volkswagen

In [7]:
newData2 = df[df.Make == 'Audi']['Model'].unique()
 
newData2

array(['100', '200', '80', '90', 'A3', 'A4 allroad', 'A4', 'A5', 'A6',
       'A7', 'A8', 'allroad quattro', 'allroad', 'Cabriolet', 'Coupe',
       'Q3', 'Q5', 'Q7', 'R8', 'RS 4', 'RS 5', 'RS 6', 'RS 7', 'S3', 'S4',
       'S5', 'S6', 'S7', 'S8', 'SQ5', 'TT RS', 'TT', 'TTS', 'V8'],
      dtype=object)

In [ ]:
# The value is 34, we could it ourselves

In [8]:
missingData = df.isnull().sum()
missingData

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [ ]:
# 5 columns have missing values

In [9]:
medValuesEngine = df['Engine Cylinders'].median()
medValuesEngine

6.0

In [10]:
frquenctValueEngine = df['Engine Cylinders'].value_counts()
frquenctValueEngine

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [ ]:
# The frequenct value of the "Engine Cylinders" is 4.0

In [11]:
NewMedian = df['Engine Cylinders'].fillna(frquenctValueEngine).median()
NewMedian

6.0

In [ ]:
# Has it changed (Mode and Median): Yes!

In [12]:
newData3 = df[df.Make == 'Lotus'][['Engine HP','Engine Cylinders']].drop_duplicates()
newData3

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [13]:
X = newData3.values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [14]:
X.T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [15]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [16]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [17]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [18]:
w = XTX_inv.dot(X.T).dot(y)
w

array([  4.59494481, -63.56432501])